spec:
  replicas: 10
  template:
    spec:
      volumes:
        - name: volume-mutant-detector
          configMap:
            name: mutant-detector-config
      containers:
        - resources:
            limits:
              cpu: 200m
              memory: 384Mi
            requests:
              cpu: 100m
              memory: 256Mi
          env:
            - name: SPRING_CONFIG_LOCATION
              value: /data/application.properties
          volumeMounts:
            - name: volume-mutant-detector
              mountPath: /data